
open science practices

+ Engagement DEI
	+ Aboriginal training 
	Ally LGBTIQ+ training 2023 1 day Macquarie University
Aboriginal Culture Safety Training 2023 1 day Macquarie University

Travelling to conferences by train

Avoid buying and reusing
Make an inventory before 
Take time to ask different labs about their resources rather than buying new ones

Long lasting computer

Online conferences

# Open science




## Ongoing commitments

+ Carefully analyse most ethical journals
Link to the table
## Past initiatives
Open science practices
Summer School
Workshop open science training 
Workshop Preregistration, data simulation 2021 1 day Malika Ihle


• Active member of SORTEE (Society for Open, Reliable and Transparent biology in
Ecology and Evolution)
- 2025: Chair, Conference Committee
- 2023-2024: Program Manager, Conference Committee
• Volunteer for Peer Community In (PCI)
- 2024-2025: Article formatting
- 2025: Data and script reviewing
• Commitment to ethical scientific publishing
- Published the final paper from my PhD in Peer Community Journal
- For my first postdoctoral paper, I could not find an ideal journal in marine biology,
so I chose Coral Reefs, which is at least supported by a scientific society
## Future commitments

# Diversity, Equity and Inclusion
## Ongoing commitments
+ Member of the DEI committee in the scientific society SORTEE
+ Check digital accessibility in my papers (use of color blindness simulator, provide alt text for images, text and contrast big enough, meaningful hyperlink texts)

# Sustainability

